const START_COUNT = "START_COUNT";
const ADD_TODO = "ADD_TODO";

//Acciones para los peror
const API_CALL_REQUEST = "API_CALL_REQUEST";
const API_CALL_SUCCESS = "API_CALL_SUCCESS";
const API_CALL_FAILURE = "API_CALL_FAILURE";

/** Exportar  */
export {
  START_COUNT,
  ADD_TODO,
  API_CALL_FAILURE,
  API_CALL_REQUEST,
  API_CALL_SUCCESS
};
